console.log("Schema & model")
console.log("run")
console.log("run")
console.log("run")
console.log("run")
console.log("run")
console.log("run")
<<<<<<< HEAD
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")

console.log("run")
console.log("in b1 branch")
console.log("in b1 branch")
console.log("in b1 branch")
console.log("in b1 branch")
console.log("in b1 branch")
console.log("in b1 branch")

