console.log("Schema & model")
console.log("run")
console.log("run")
console.log("run")
console.log("run")
console.log("run")
console.log("run")

console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")
console.log("in main branch")

console.log("run")
console.log("in b1 branch")
console.log("in b1 branch")
console.log("in b1 branch")
console.log("in b1 branch")
console.log("in b1 branch")
console.log("in b1 branch")


console.log("new branch in m4 commit called b2")
console.log("new branch in m4 commit called b2")
console.log("new branch in m4 commit called b2")
console.log("new branch in m4 commit called b2")
console.log("new branch in m4 commit called b2")
console.log("new branch in m4 commit called b2")
console.log("new branch in m4 commit called b2")
console.log("new branch in m4 commit called b2")
console.log("first commit in b2")
console.log("first commit in b2")
console.log("first commit in b2")
console.log("first commit in b2")
console.log("first commit in b2")
console.log("first commit in b2")
console.log("second commit in b2")
console.log("second commit in b2")
console.log("second commit in b2")
console.log("second commit in b2")
console.log("second commit in b2")
